#!/usr/bin/env bash

function parse_input() {
  # jq reads from stdin so we don't have to set up any inputs, but let's validate the outputs
  eval "$(jq -r '@sh "export CONTROL_PLANE_NODE=\(.control_plane_node) USER=\(.user) PASSWORD=\(.password)"')"
  if [[ -z "${CONTROL_PLANE_NODE}" ]]; then export CONTROL_PLANE_NODE=none; fi
  if [[ -z "${USER}" ]]; then export USER=none; fi
  if [[ -z "${PASSWORD}" ]]; then export PASSWORD=none; fi
}

function get_kubeconfig(){
    kubeconfig_content=$(sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USER@$CONTROL_PLANE_NODE cat /etc/kubernetes/admin.conf)
    jq -n \
      --arg kubeconfig "$kubeconfig_content" \
      '{"kubeconfig":$kubeconfig}'
}

parse_input
get_kubeconfig